name: Update Starship

on:
  schedule:
    # Runs at 20:00 UTC every day. 
    - cron: 0 20 * * *
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      starship: ${{ steps.starship.outputs.release }}
      local: ${{ steps.local.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - id: starship
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: starship
          repo: starship
          excludes: prerelease, draft
      - name: Local version
        id: local
        shell: bash
        run: |
          if test -f ".config/fish/store/starship/version"; then
              echo "::set-output name=version::$(cat .config/fish/store/starship/version)"
          fi
  update-starship:
    runs-on: ubuntu-latest
    needs: check-version
    if: ${{ needs.check-version.outputs.starship != needs.check-version.outputs.local }}
    steps:
      - name: Print versions
        run: |
          echo "Remote: ${{ needs.check-version.outputs.starship }}"
          echo "Local: ${{ needs.check-version.outputs.local }}"
      #- uses: actions/checkout@v3
