name: Fetch Starship

on:
  schedule:
    # Runs at 20:00 UTC every day. 
    - cron: 0 20 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: starship
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: starship
          repo: starship
          excludes: prerelease, draft
      - name: Print version
        run: |
          echo ${{ steps.starship.outputs.release }}
